// Code generated by mockery; DO NOT EDIT
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockKeyValueStore creates a new instance of MockKeyValueStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations
// The first argument is typically a *testing.T value
func NewMockKeyValueStore(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockKeyValueStore {
	mock := &MockKeyValueStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKeyValueStore is an autogenerated mock type for the KeyValueStore type
type MockKeyValueStore struct {
	mock.Mock
}

type MockKeyValueStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKeyValueStore) EXPECT() *MockKeyValueStore_Expecter {
	return &MockKeyValueStore_Expecter{mock: &_m.Mock}
}

// Del provides a mock function for the type MockKeyValueStore
func (_mock *MockKeyValueStore) Del(ctx context.Context, keys ...string) error {
	var tmpRet mock.Arguments
	if len(keys) > 0 {
		tmpRet = _mock.Called(ctx, keys)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Del")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) error); ok {
		r0 = returnFunc(ctx, keys...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKeyValueStore_Del_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Del'
type MockKeyValueStore_Del_Call struct {
	*mock.Call
}

// Del is a helper method to define mock.On call
//   - ctx context.Context
//   - keys ...string
func (_e *MockKeyValueStore_Expecter) Del(ctx interface{}, keys ...interface{}) *MockKeyValueStore_Del_Call {
	return &MockKeyValueStore_Del_Call{Call: _e.mock.On("Del",
		append([]interface{}{ctx}, keys...)...)}
}

func (_c *MockKeyValueStore_Del_Call) Run(run func(ctx context.Context, keys ...string)) *MockKeyValueStore_Del_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockKeyValueStore_Del_Call) Return(err error) *MockKeyValueStore_Del_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKeyValueStore_Del_Call) RunAndReturn(run func(ctx context.Context, keys ...string) error) *MockKeyValueStore_Del_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockKeyValueStore
func (_mock *MockKeyValueStore) Get(ctx context.Context, key string) ([]byte, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeyValueStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockKeyValueStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockKeyValueStore_Expecter) Get(ctx interface{}, key interface{}) *MockKeyValueStore_Get_Call {
	return &MockKeyValueStore_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockKeyValueStore_Get_Call) Run(run func(ctx context.Context, key string)) *MockKeyValueStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeyValueStore_Get_Call) Return(bytes []byte, err error) *MockKeyValueStore_Get_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockKeyValueStore_Get_Call) RunAndReturn(run func(ctx context.Context, key string) ([]byte, error)) *MockKeyValueStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockKeyValueStore
func (_mock *MockKeyValueStore) Set(ctx context.Context, key string, value []byte, ttl time.Duration) error {
	ret := _mock.Called(ctx, key, value, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, time.Duration) error); ok {
		r0 = returnFunc(ctx, key, value, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKeyValueStore_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockKeyValueStore_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value []byte
//   - ttl time.Duration
func (_e *MockKeyValueStore_Expecter) Set(ctx interface{}, key interface{}, value interface{}, ttl interface{}) *MockKeyValueStore_Set_Call {
	return &MockKeyValueStore_Set_Call{Call: _e.mock.On("Set", ctx, key, value, ttl)}
}

func (_c *MockKeyValueStore_Set_Call) Run(run func(ctx context.Context, key string, value []byte, ttl time.Duration)) *MockKeyValueStore_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockKeyValueStore_Set_Call) Return(err error) *MockKeyValueStore_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKeyValueStore_Set_Call) RunAndReturn(run func(ctx context.Context, key string, value []byte, ttl time.Duration) error) *MockKeyValueStore_Set_Call {
	_c.Call.Return(run)
	return _c
}
