// Code generated by mockery; DO NOT EDIT
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPubSubStore creates a new instance of MockPubSubStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations
// The first argument is typically a *testing.T value
func NewMockPubSubStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPubSubStore {
	mock := &MockPubSubStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPubSubStore is an autogenerated mock type for the PubSubStore type
type MockPubSubStore struct {
	mock.Mock
}

type MockPubSubStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPubSubStore) EXPECT() *MockPubSubStore_Expecter {
	return &MockPubSubStore_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function for the type MockPubSubStore
func (_mock *MockPubSubStore) Publish(ctx context.Context, channel string, message string) error {
	ret := _mock.Called(ctx, channel, message)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, channel, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPubSubStore_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockPubSubStore_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - channel string
//   - message string
func (_e *MockPubSubStore_Expecter) Publish(ctx interface{}, channel interface{}, message interface{}) *MockPubSubStore_Publish_Call {
	return &MockPubSubStore_Publish_Call{Call: _e.mock.On("Publish", ctx, channel, message)}
}

func (_c *MockPubSubStore_Publish_Call) Run(run func(ctx context.Context, channel string, message string)) *MockPubSubStore_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPubSubStore_Publish_Call) Return(err error) *MockPubSubStore_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPubSubStore_Publish_Call) RunAndReturn(run func(ctx context.Context, channel string, message string) error) *MockPubSubStore_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function for the type MockPubSubStore
func (_mock *MockPubSubStore) Subscribe(ctx context.Context, channel string) (<-chan string, error) {
	ret := _mock.Called(ctx, channel)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 <-chan string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (<-chan string, error)); ok {
		return returnFunc(ctx, channel)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) <-chan string); ok {
		r0 = returnFunc(ctx, channel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, channel)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPubSubStore_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockPubSubStore_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - channel string
func (_e *MockPubSubStore_Expecter) Subscribe(ctx interface{}, channel interface{}) *MockPubSubStore_Subscribe_Call {
	return &MockPubSubStore_Subscribe_Call{Call: _e.mock.On("Subscribe", ctx, channel)}
}

func (_c *MockPubSubStore_Subscribe_Call) Run(run func(ctx context.Context, channel string)) *MockPubSubStore_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPubSubStore_Subscribe_Call) Return(stringCh <-chan string, err error) *MockPubSubStore_Subscribe_Call {
	_c.Call.Return(stringCh, err)
	return _c
}

func (_c *MockPubSubStore_Subscribe_Call) RunAndReturn(run func(ctx context.Context, channel string) (<-chan string, error)) *MockPubSubStore_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}
