version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/integration"
    schedule:
      interval: "weekly"
    groups:
      shared-dependencies:
        group-by: "dependency-name"
    labels:
      - "dependencies"
      - "go"
