version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "go"
  - package-ecosystem: "gomod"
    directory: "/integration"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "go"
