all: false
force-file-write: true
formatter: goimports
log-level: info
template: testify

packages:
  github.com/wahrwelt-kit/go-cachekit:
    interfaces:
      KeyValueStore:
        config:
          dir: "mock"
          filename: "KeyValueStore.go"
          pkgname: "mock"
          structname: "MockKeyValueStore"
      PubSubStore:
        config:
          dir: "mock"
          filename: "PubSubStore.go"
          pkgname: "mock"
          structname: "MockPubSubStore"
